version: '3'
networks:
  group:

services:
  db_server:
    container_name: db_server
    build:
      context: nodes/db_server
    ports:
      - "7000:7000"
    networks:
      - group

  web_server:
    container_name: web_server
    build:
      context: nodes/web_server
    ports:
      - "80:5000"
    networks:
      - group